language: java
sudo: false
install: true
jdk: oraclejdk11
node_js: 10.16.0
dist: trusty

before_install: if [[ `npm -v` != 6.9* ]]; then npm i -g npm@6.9; fi

env:
  - TARGET=BUILD
  - TARGET=ANALYZE

matrix:
  fast_finish: true

script: ./travis.sh

cache:
  directories:
    - $HOME/.sonar/cache
    - $HOME/sonar-scanner-3.0.3.778-linux
