language: node_js
sudo: false
install: true
jdk: oraclejdk11
node_js: "10.16"
dist: trusty

before_install:
  - if [[ `yarn -v` != 1.15* ]]; then curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2 && export PATH="$HOME/.yarn/bin:$PATH"; fi
  - if [[ `./tools/jfrog -v` != jfrog\ version* ]]; then curl -fL https://getcli.jfrog.io | sh && mv jfrog $HOME/tools/jfrog && export PATH="$HOME/tools:$PATH"; fi

env:
  - TARGET=ANALYZE
  - TARGET=BUILD

matrix:
  fast_finish: true

script: ./travis.sh

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/tools
    - $HOME/.sonar/cache
    - $HOME/sonar-scanner-3.0.3.778-linux

notifications:
  email: false
  webhooks:
    - secure: "kG4O5QqNIi5U0jBfAbILMQKFFwc6+WOgjnAXjqEDFK2I4K2i2tk7eqS0w/awfrUbTYvjrE6K3F1g5zHmqV8kuHzFJHgkM8R8pm8OzHSGdz5ofRq5eiIU5ozYvgoJIv+jB9UyvcdecCjQF/kbnEsMnRDp14Gr60n+oj/d0MpRiS/WRIu438p+q6Hn34GQzSLqLd375vL8u0iJPKrShsYmkYUJNIAtSE8E6l4JJfaMbT3BQ52xiN4xQPYMfcNplxsLaWuI5BGJ03LQ4F9qoHSPZ7Dm/fJnZG7TKXI9VhYhmSZwRfhyWxrxO5BodLwVwdu7U4wD1U28SzeHMotBS8vDXNYtIukvipPDVjfiBAjfMfeMcuit13/+Jj7sFbckVyERZPJh6ADImohHd8DKtzzKx7g/6eNhBu99fFsxHDK10vl1i//3vVKnytqz59HtlhJFHtTc77wjZ5Pkwl2Q5UsPVTSFY5+uxlVnx+gMA4RF2/ag1qTu/ZxCLFL0GoTGl0Ucqh50tZAU+53Zx6/t/ZkpJucS/+p7hcp7Pjv0CXpoDa2jJYkqipj42Fk5NMm9OFXWUyydMKPYpKNGc6iQTQCJIMekAroOlsjnZQu78H+4QvRI9a5N1J0jEJ6lVNKIgJmTwlgc/xFi3VjvyezkF2yQM64lkFbeR0/buFOswylWPUg="
  on_start: always

