language: java
sudo: false
install: true
jdk: oraclejdk11
node_js: 10.16.0
dist: trusty

env:
  - TARGET=BUILD
  - TARGET=WEB_TESTS

matrix:
  fast_finish: true

script: ./travis.sh

cache:
  directories:
    - $HOME/.sonar/cache
    - $HOME/sonar-scanner-3.0.3.778-linux
